"""empty message

Revision ID: 987a994a7ae1
Revises: 591d34f4d471
Create Date: 2023-01-27 21:49:47.297685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '987a994a7ae1'
down_revision = '591d34f4d471'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=250),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=250),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)

    # ### end Alembic commands ###
